[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
logfile=%(ENV_HOME)s/Library/Logs/supervisor/supervisord.log
logfile_maxbytes=10MB
loglevel=info
nodaemon=false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[include]
files = conf.d/*.conf
