[program:bookmark-processor]
command=%(ENV_HOME)s/.local/bin/uv run uvicorn app.api:app --port 8484
directory=%(ENV_HOME)s/Documents/all_code/bookmark-content-processor
autostart=true
autorestart=true
stdout_logfile=%(ENV_HOME)s/Library/Logs/supervisor/bookmark-processor.log
stderr_logfile=%(ENV_HOME)s/Library/Logs/supervisor/bookmark-processor.error.log
